//
//  TripsManagementView.swift
//  LocTrac
//
//  Comprehensive trips management with editing capabilities
//

import SwiftUI

struct TripsManagementView: View {
    @EnvironmentObject var store: DataStore
    @Environment(\.dismiss) private var dismiss
    @State private var selectedYear: String = "All Time"
    @State private var selectedTrip: Trip?
    @State private var showingTripEditor = false
    @State private var searchText = ""
    
    private var availableYears: [String] {
        let years = Set(store.trips.map { Calendar.current.component(.year, from: $0.departureDate) })
        return ["All Time"] + years.sorted(by: >).map { String($0) }
    }
    
    private var filteredTrips: [Trip] {
        var trips = selectedYear == "All Time"
            ? store.trips
            : store.trips.filter { Calendar.current.component(.year, from: $0.departureDate) == Int(selectedYear) }
        
        if !searchText.isEmpty {
            trips = trips.filter { trip in
                let fromEvent = store.events.first(where: { $0.id == trip.fromEventID })
                let toEvent = store.events.first(where: { $0.id == trip.toEventID })
                let fromName = fromEvent?.location.name ?? ""
                let toName = toEvent?.location.name ?? ""
                return fromName.localizedCaseInsensitiveContains(searchText) ||
                       toName.localizedCaseInsensitiveContains(searchText) ||
                       trip.mode.rawValue.localizedCaseInsensitiveContains(searchText)
            }
        }
        
        return trips.sorted { $0.departureDate > $1.departureDate }
    }
    
    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                // Search bar
                searchBar
                
                // Year filter
                yearFilterSection
                
                // Trip stats
                statsSection
                
                // Trips list
                if filteredTrips.isEmpty {
                    emptyState
                } else {
                    tripsList
                }
            }
            .navigationTitle("Manage Trips")
            .navigationBarTitleDisplayMode(.large)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
            .sheet(item: $selectedTrip) { trip in
                if let fromEvent = store.events.first(where: { $0.id == trip.fromEventID }),
                   let toEvent = store.events.first(where: { $0.id == trip.toEventID }) {
                    TripEditorSheet(trip: trip, fromEvent: fromEvent, toEvent: toEvent)
                        .environmentObject(store)
                }
            }
        }
    }
    
    private var searchBar: some View {
        HStack {
            Image(systemName: "magnifyingglass")
                .foregroundColor(.gray)
            TextField("Search trips...", text: $searchText)
                .textFieldStyle(.plain)
            if !searchText.isEmpty {
                Button {
                    searchText = ""
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .foregroundColor(.gray)
                }
            }
        }
        .padding(8)
        .background(Color(.systemGray6))
        .cornerRadius(10)
        .padding()
    }
    
    private var yearFilterSection: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 12) {
                ForEach(availableYears, id: \.self) { year in
                    Button {
                        withAnimation(.spring(response: 0.3)) {
                            selectedYear = year
                        }
                    } label: {
                        Text(year)
                            .font(.subheadline)
                            .fontWeight(selectedYear == year ? .semibold : .regular)
                            .foregroundColor(selectedYear == year ? .white : .primary)
                            .padding(.horizontal, 16)
                            .padding(.vertical, 8)
                            .background(
                                RoundedRectangle(cornerRadius: 20)
                                    .fill(selectedYear == year ? Color.blue : Color(.tertiarySystemBackground))
                            )
                    }
                }
            }
            .padding(.horizontal)
        }
        .padding(.bottom, 8)
    }
    
    private var statsSection: some View {
        HStack(spacing: 12) {
            StatBox(title: "Total", value: "\(filteredTrips.count)", color: .blue)
            StatBox(title: "Auto", value: "\(filteredTrips.filter(\.isAutoGenerated).count)", color: .orange)
            StatBox(title: "Manual", value: "\(filteredTrips.filter { !$0.isAutoGenerated }.count)", color: .green)
        }
        .padding()
        .background(Color(.secondarySystemBackground))
    }
    
    private var tripsList: some View {
        List {
            ForEach(filteredTrips) { trip in
                TripManagementRow(trip: trip, store: store)
                    .contentShape(Rectangle())
                    .onTapGesture {
                        selectedTrip = trip
                    }
            }
            .onDelete(perform: deleteTrips)
        }
        .listStyle(.plain)
    }
    
    private var emptyState: some View {
        VStack(spacing: 16) {
            Image(systemName: "airplane.circle")
                .font(.system(size: 64))
                .foregroundColor(.gray)
            Text("No Trips Found")
                .font(.title2)
                .fontWeight(.semibold)
            if !searchText.isEmpty {
                Text("Try a different search")
                    .font(.subheadline)
                    .foregroundColor(.secondary)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
    
    private func deleteTrips(at offsets: IndexSet) {
        for index in offsets {
            store.deleteTrip(filteredTrips[index])
        }
    }
}

// MARK: - Trip Management Row
struct TripManagementRow: View {
    let trip: Trip
    let store: DataStore
    
    private var fromEvent: Event? {
        store.events.first(where: { $0.id == trip.fromEventID })
    }
    
    private var toEvent: Event? {
        store.events.first(where: { $0.id == trip.toEventID })
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Header with date and badges
            HStack {
                Text(trip.departureDate.formatted(date: .abbreviated, time: .omitted))
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                Spacer()
                
                if trip.isAutoGenerated {
                    Text("AUTO")
                        .font(.caption2)
                        .fontWeight(.semibold)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(Color.orange.opacity(0.2))
                        .foregroundColor(.orange)
                        .cornerRadius(4)
                }
                
                modeBadge
            }
            
            // Route
            HStack(spacing: 8) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(fromEvent?.location.name ?? "Unknown")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    if let city = fromEvent?.city {
                        Text(city)
                            .font(.caption2)
                            .foregroundColor(.secondary)
                    }
                }
                
                Image(systemName: "arrow.right")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                VStack(alignment: .leading, spacing: 2) {
                    Text(toEvent?.location.name ?? "Unknown")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    if let city = toEvent?.city {
                        Text(city)
                            .font(.caption2)
                            .foregroundColor(.secondary)
                    }
                }
            }
            
            // Stats row
            HStack(spacing: 16) {
                Label("\(Int(trip.distance)) mi", systemImage: "road.lanes")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                Label("\(Int(trip.co2Emissions)) lbs CO₂", systemImage: "cloud.fill")
                    .font(.caption)
                    .foregroundColor(.orange)
                
                if trip.durationInHours > 0 {
                    Label(String(format: "%.1fh", trip.durationInHours), systemImage: "clock")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
            
            // Notes preview
            if !trip.notes.isEmpty {
                Text(trip.notes)
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .lineLimit(1)
            }
        }
        .padding(.vertical, 4)
    }
    
    private var modeBadge: some View {
        HStack(spacing: 4) {
            Image(systemName: trip.mode.icon)
            Text(trip.mode.rawValue)
        }
        .font(.caption)
        .fontWeight(.semibold)
        .padding(.horizontal, 10)
        .padding(.vertical, 4)
        .background(modeColor.opacity(0.2))
        .foregroundColor(modeColor)
        .cornerRadius(8)
    }
    
    private var modeColor: Color {
        switch trip.mode {
        case .flying: return .blue
        case .driving: return .green
        case .train: return .purple
        case .bus: return .orange
        case .boat: return .cyan
        case .bicycle: return .mint
        case .walking: return .teal
        case .other: return .gray
        }
    }
}

// MARK: - Trip Editor Sheet
struct TripEditorSheet: View {
    @EnvironmentObject var store: DataStore
    @Environment(\.dismiss) private var dismiss
    
    let trip: Trip
    let fromEvent: Event
    let toEvent: Event
    
    @State private var transportMode: Trip.TransportMode
    @State private var distance: Double
    @State private var notes: String
    @State private var departureDate: Date
    @State private var arrivalDate: Date
    
    init(trip: Trip, fromEvent: Event, toEvent: Event) {
        self.trip = trip
        self.fromEvent = fromEvent
        self.toEvent = toEvent
        
        _transportMode = State(initialValue: trip.mode)
        _distance = State(initialValue: trip.distance)
        _notes = State(initialValue: trip.notes)
        _departureDate = State(initialValue: trip.departureDate)
        _arrivalDate = State(initialValue: trip.arrivalDate)
    }
    
    var body: some View {
        NavigationStack {
            Form {
                // Route info (read-only)
                Section("Route") {
                    HStack {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(fromEvent.location.name)
                                .fontWeight(.semibold)
                            if let city = fromEvent.city {
                                Text(city)
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                        }
                        
                        Spacer()
                        
                        Image(systemName: "arrow.right")
                            .foregroundColor(.blue)
                        
                        Spacer()
                        
                        VStack(alignment: .trailing, spacing: 4) {
                            Text(toEvent.location.name)
                                .fontWeight(.semibold)
                            if let city = toEvent.city {
                                Text(city)
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                }
                
                // Transport mode
                Section("Transport Mode") {
                    Picker("Mode", selection: $transportMode) {
                        ForEach(Trip.TransportMode.allCases, id: \.self) { mode in
                            HStack {
                                Image(systemName: mode.icon)
                                Text(mode.rawValue)
                            }
                            .tag(mode)
                        }
                    }
                    .pickerStyle(.menu)
                }
                
                // Distance
                Section {
                    HStack {
                        Text("Distance")
                        Spacer()
                        TextField("Miles", value: $distance, format: .number)
                            .keyboardType(.decimalPad)
                            .multilineTextAlignment(.trailing)
                            .frame(width: 100)
                        Text("mi")
                            .foregroundColor(.secondary)
                    }
                } header: {
                    Text("Distance")
                } footer: {
                    Text("Estimated CO₂: \(Int(distance * transportMode.co2PerMile)) lbs")
                        .foregroundColor(.orange)
                }
                
                // Dates
                Section("Travel Dates") {
                    DatePicker("Departure", selection: $departureDate)
                    DatePicker("Arrival", selection: $arrivalDate, in: departureDate...)
                }
                
                // Notes
                Section("Notes") {
                    TextEditor(text: $notes)
                        .frame(minHeight: 80)
                }
                
                // Trip info
                Section("Trip Info") {
                    HStack {
                        Text("Created")
                        Spacer()
                        Text(trip.isAutoGenerated ? "Auto-generated" : "Manual")
                            .foregroundColor(.secondary)
                    }
                    
                    HStack {
                        Text("Modified")
                        Spacer()
                        Text(trip.modifiedAt.formatted(date: .abbreviated, time: .shortened))
                            .foregroundColor(.secondary)
                    }
                }
            }
            .navigationTitle("Edit Trip")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        saveChanges()
                    }
                    .disabled(distance <= 0)
                }
            }
        }
    }
    
    private func saveChanges() {
        trip.mode = transportMode
        trip.distance = distance
        trip.notes = notes
        trip.departureDate = departureDate
        trip.arrivalDate = arrivalDate
        trip.recalculateCO2()
        
        store.save()
        dismiss()
    }
}

// MARK: - Stat Box
struct StatBox: View {
    let title: String
    let value: String
    let color: Color
    
    var body: some View {
        VStack(spacing: 4) {
            Text(value)
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(color)
            Text(title)
                .font(.caption)
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 8)
        .background(Color(.tertiarySystemBackground))
        .cornerRadius(8)
    }
}

// MARK: - Preview
struct TripsManagementView_Previews: PreviewProvider {
    static var previews: some View {
        TripsManagementView()
            .environmentObject(DataStore())
    }
}
