//
//  Trip.swift
//  LocTrac
//
//  Model representing travel between locations
//

import Foundation
import CoreLocation
import SwiftData

@Model
final class Trip {
    var id: UUID
    var fromEventID: String  // Event IDs are Strings
    var toEventID: String    // Event IDs are Strings
    var departureDate: Date
    var arrivalDate: Date
    var distance: Double // miles
    var transportMode: String // TransportMode rawValue
    var co2Emissions: Double // pounds
    var notes: String
    var isAutoGenerated: Bool
    var createdAt: Date
    var modifiedAt: Date
    
    init(
        id: UUID = UUID(),
        fromEventID: String,
        toEventID: String,
        departureDate: Date,
        arrivalDate: Date,
        distance: Double,
        transportMode: TransportMode,
        co2Emissions: Double? = nil,
        notes: String = "",
        isAutoGenerated: Bool = false
    ) {
        self.id = id
        self.fromEventID = fromEventID
        self.toEventID = toEventID
        self.departureDate = departureDate
        self.arrivalDate = arrivalDate
        self.distance = distance
        self.transportMode = transportMode.rawValue
        self.co2Emissions = co2Emissions ?? (distance * transportMode.co2PerMile)
        self.notes = notes
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
        self.modifiedAt = Date()
    }
    
    // Computed property for type-safe transport mode
    var mode: TransportMode {
        get { TransportMode(rawValue: transportMode) ?? .other }
        set { transportMode = newValue.rawValue }
    }
    
    // Update CO2 emissions based on current distance and mode
    func recalculateCO2() {
        co2Emissions = distance * mode.co2PerMile
        modifiedAt = Date()
    }
}

// MARK: - Transport Mode Enum
extension Trip {
    enum TransportMode: String, Codable, CaseIterable {
        case flying = "Flying"
        case driving = "Driving"
        case train = "Train"
        case bus = "Bus"
        case boat = "Boat"
        case bicycle = "Bicycle"
        case walking = "Walking"
        case other = "Other"
        
        var co2PerMile: Double {
            switch self {
            case .flying:
                return 0.9  // ~0.9 lbs CO2 per mile (commercial flight)
            case .driving:
                return 0.89 // ~0.89 lbs CO2 per mile (average car)
            case .train:
                return 0.14 // ~0.14 lbs CO2 per mile (passenger rail)
            case .bus:
                return 0.29 // ~0.29 lbs CO2 per mile (motorcoach)
            case .boat:
                return 0.25 // ~0.25 lbs CO2 per mile (ferry/cruise)
            case .bicycle:
                return 0.0  // Zero emissions
            case .walking:
                return 0.0  // Zero emissions
            case .other:
                return 0.5  // Default estimate
            }
        }
        
        var icon: String {
            switch self {
            case .flying:
                return "airplane"
            case .driving:
                return "car.fill"
            case .train:
                return "train.side.front.car"
            case .bus:
                return "bus.fill"
            case .boat:
                return "ferry.fill"
            case .bicycle:
                return "bicycle"
            case .walking:
                return "figure.walk"
            case .other:
                return "questionmark.circle"
            }
        }
        
        var color: String {
            switch self {
            case .flying:
                return "blue"
            case .driving:
                return "green"
            case .train:
                return "purple"
            case .bus:
                return "orange"
            case .boat:
                return "cyan"
            case .bicycle, .walking:
                return "mint"
            case .other:
                return "gray"
            }
        }
        
        // Auto-detect transport mode based on distance
        static func detectMode(distance: Double) -> TransportMode {
            if distance <= 3 {
                return .walking  // Less than 3 miles
            } else if distance <= 100 {
                return .driving  // 3-100 miles
            } else {
                return .flying   // Over 100 miles
            }
        }
    }
}

// MARK: - Computed Properties
extension Trip {
    var durationInHours: Double {
        arrivalDate.timeIntervalSince(departureDate) / 3600
    }
    
    var formattedDistance: String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 1
        return formatter.string(from: NSNumber(value: distance)) ?? "\(Int(distance))"
    }
    
    var formattedCO2: String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 0
        return formatter.string(from: NSNumber(value: co2Emissions)) ?? "\(Int(co2Emissions))"
    }
}

// MARK: - Comparable for Sorting
extension Trip: Comparable {
    static func < (lhs: Trip, rhs: Trip) -> Bool {
        lhs.departureDate < rhs.departureDate
    }
}
