//
//  TripMigrationUtility.swift
//  LocTrac
//
//  Utility to migrate existing events into trips
//

import Foundation
import CoreLocation

struct TripMigrationUtility {
    
    /// Migrate all existing events to create trips where location changes
    static func migrateEventsToTrips(events: [Event]) -> [Trip] {
        // Sort events chronologically
        let sortedEvents = events
            .filter { hasValidCoordinates($0) }
            .sorted { $0.date < $1.date }
        
        guard sortedEvents.count > 1 else { return [] }
        
        var generatedTrips: [Trip] = []
        
        // Iterate through consecutive events
        for i in 0..<(sortedEvents.count - 1) {
            let currentEvent = sortedEvents[i]
            let nextEvent = sortedEvents[i + 1]
            
            // Check if this represents a location change (actual trip)
            guard shouldCreateTrip(from: currentEvent, to: nextEvent) else {
                continue
            }
            
            // Calculate trip details
            let distance = calculateDistance(from: currentEvent, to: nextEvent)
            let transportMode = Trip.TransportMode.detectMode(distance: distance)
            
            let trip = Trip(
                fromEventID: currentEvent.id,
                toEventID: nextEvent.id,
                departureDate: currentEvent.date,
                arrivalDate: nextEvent.date,
                distance: distance,
                transportMode: transportMode,
                notes: "Auto-generated during migration",
                isAutoGenerated: true
            )
            
            generatedTrips.append(trip)
        }
        
        print("✅ Migration: Generated \(generatedTrips.count) trips from \(sortedEvents.count) events")
        return generatedTrips
    }
    
    /// Check if event has valid coordinates
    private static func hasValidCoordinates(_ event: Event) -> Bool {
        let hasEventCoords = event.latitude != 0.0 && event.longitude != 0.0
        let hasLocationCoords = event.location.latitude != 0.0 && event.location.longitude != 0.0
        return hasEventCoords || hasLocationCoords
    }
    
    /// Determine if a trip should be created between two events
    private static func shouldCreateTrip(from current: Event, to next: Event) -> Bool {
        let currentLocationID = current.location.id
        let nextLocationID = next.location.id
        
        let currentIsOther = current.location.name == "Other"
        let nextIsOther = next.location.name == "Other"
        
        // Check if locations are different
        if currentIsOther && nextIsOther {
            // Both are "Other" - check if coordinates are significantly different
            let distance = calculateDistance(from: current, to: next)
            return distance > 1.0 // More than 1 mile apart
        } else if currentIsOther || nextIsOther {
            // One is "Other" and one is a named location - always different
            return true
        } else {
            // Both are named locations - check location IDs
            return currentLocationID != nextLocationID
        }
    }
    
    /// Calculate distance between two events in miles
    private static func calculateDistance(from current: Event, to next: Event) -> Double {
        let currentCoord = getCoordinates(for: current)
        let nextCoord = getCoordinates(for: next)
        
        let location1 = CLLocation(latitude: currentCoord.latitude, longitude: currentCoord.longitude)
        let location2 = CLLocation(latitude: nextCoord.latitude, longitude: nextCoord.longitude)
        
        let distanceInMeters = location1.distance(from: location2)
        let distanceInMiles = distanceInMeters * 0.000621371
        
        return distanceInMiles
    }
    
    /// Get coordinates for an event (from event or location)
    private static func getCoordinates(for event: Event) -> CLLocationCoordinate2D {
        if event.latitude != 0.0 && event.longitude != 0.0 {
            return CLLocationCoordinate2D(latitude: event.latitude, longitude: event.longitude)
        } else {
            return CLLocationCoordinate2D(
                latitude: event.location.latitude,
                longitude: event.location.longitude
            )
        }
    }
    
    /// Generate a trip suggestion for a new event
    static func suggestTrip(from previousEvent: Event, to newEvent: Event) -> Trip? {
        // Check if both events have valid coordinates
        guard hasValidCoordinates(previousEvent), hasValidCoordinates(newEvent) else {
            return nil
        }
        
        // Check if this represents a location change
        guard shouldCreateTrip(from: previousEvent, to: newEvent) else {
            return nil
        }
        
        // Calculate trip details
        let distance = calculateDistance(from: previousEvent, to: newEvent)
        
        // Don't suggest trips for very short distances (less than 0.5 miles)
        guard distance > 0.5 else { return nil }
        
        let transportMode = Trip.TransportMode.detectMode(distance: distance)
        
        return Trip(
            fromEventID: previousEvent.id,
            toEventID: newEvent.id,
            departureDate: previousEvent.date,
            arrivalDate: newEvent.date,
            distance: distance,
            transportMode: transportMode,
            notes: "",
            isAutoGenerated: true
        )
    }
}
