import Foundation

struct Import: Codable {
    struct Event: Codable {
        var locationID: String
        let id: String
        var eventType: String
        let date: Date
        var city: String?           // v1.5: Now optional (backward compat)
        var latitude: Double
        var longitude: Double
        var country: String?        // Country field for events
        var state: String?          // v1.5: State/province (optional for backward compat)
        var note: String
        var people: [Person]?       // optional for backward compatibility
        var activityIDs: [String]?  // optional for backward compatibility
        var affirmationIDs: [String]? // optional for backward compatibility
    }
    
    struct Location: Codable {
        let id: String
        var name: String
        var city: String?
        var state: String?          // v1.5: State/province (optional for backward compat)
        var latitude: Double
        var longitude: Double
        var country: String?        // Country name
        var countryCode: String?    // v1.5: ISO country code (optional for backward compat)
        var theme: String
        var imageIDs: [String]?     // existing
        var customColorHex: String? // optional custom color (backward compatible)
    }
    
    struct ActivityData: Codable {
        let id: String
        let name: String
    }
    
    struct AffirmationData: Codable {
        let id: String
        let text: String
        let category: String
        let createdDate: Date
        let color: String
        let isFavorite: Bool
    }
    
    struct TripData: Codable {
        let id: UUID
        let fromEventID: String  // Event IDs are Strings
        let toEventID: String    // Event IDs are Strings
        let departureDate: Date
        let arrivalDate: Date
        let distance: Double
        let transportMode: String
        let co2Emissions: Double
        let notes: String
        let isAutoGenerated: Bool
    }
    
    let events: [Event]
    let locations: [Location]
    let activities: [ActivityData]? // optional for old seed files
    let affirmations: [AffirmationData]? // optional for old seed files
    let trips: [TripData]? // optional for old seed files
}

struct Export: Codable {
    let locations: [LocationData]
    let events: [EventData]
    let activities: [ActivityData] // NEW
    let affirmations: [AffirmationData] // NEW
    let trips: [TripData] // NEW
    
    // Tolerant decoder for legacy backups missing activities/affirmations/trips
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.locations = try container.decode([LocationData].self, forKey: .locations)
        self.events = try container.decode([EventData].self, forKey: .events)
        self.activities = (try? container.decode([ActivityData].self, forKey: .activities)) ?? []
        self.affirmations = (try? container.decode([AffirmationData].self, forKey: .affirmations)) ?? []
        self.trips = (try? container.decode([TripData].self, forKey: .trips)) ?? []
    }
    
    init(locations: [Location], events: [Event], activities: [Activity], affirmations: [Affirmation], trips: [Trip]) {
        self.locations = locations.map {
            LocationData(id: $0.id,
                         name: $0.name,
                         city: $0.city,
                         state: $0.state,           // v1.5
                         latitude: $0.latitude,
                         longitude: $0.longitude,
                         country: $0.country,
                         countryCode: $0.countryCode, // v1.5
                         theme: $0.theme.rawValue,
                         imageIDs: $0.imageIDs,
                         customColorHex: $0.customColorHex)
        }
        self.events = events.map {
            EventData(locationID: $0.location.id,
                      id: $0.id,
                      eventType: $0.eventType,
                      date: $0.date,
                      city: $0.city,            // v1.5: City for "Other" events
                      latitude: $0.latitude,
                      longitude: $0.longitude,
                      country: $0.country,
                      state: $0.state,          // v1.5
                      note: $0.note,
                      people: $0.people,
                      activityIDs: $0.activityIDs,
                      affirmationIDs: $0.affirmationIDs)
        }
        self.activities = activities.map { ActivityData(id: $0.id, name: $0.name) }
        self.affirmations = affirmations.map {
            AffirmationData(
                id: $0.id,
                text: $0.text,
                category: $0.category.rawValue,
                createdDate: $0.createdDate,
                color: $0.color,
                isFavorite: $0.isFavorite
            )
        }
        self.trips = trips.map {
            TripData(
                id: $0.id,
                fromEventID: $0.fromEventID,
                toEventID: $0.toEventID,
                departureDate: $0.departureDate,
                arrivalDate: $0.arrivalDate,
                distance: $0.distance,
                transportMode: $0.transportMode,
                co2Emissions: $0.co2Emissions,
                notes: $0.notes,
                isAutoGenerated: $0.isAutoGenerated
            )
        }
    }
    
    struct LocationData: Codable {
        let id: String
        let name: String
        let city: String?
        let state: String?          // v1.5
        let latitude: Double
        let longitude: Double
        let country: String?
        let countryCode: String?    // v1.5
        let theme: String
        let imageIDs: [String]?
        let customColorHex: String?
    }
    
    struct EventData: Codable {
        let locationID: String
        let id: String
        var eventType: String
        let date: Date
        let city: String?           // v1.5: City for "Other" events
        let latitude: Double
        let longitude: Double
        let country: String?
        let state: String?          // v1.5
        let note: String
        let people: [Person]?
        let activityIDs: [String]
        let affirmationIDs: [String]
    }
    
    struct ActivityData: Codable {
        let id: String
        let name: String
    }
    
    struct AffirmationData: Codable {
        let id: String
        let text: String
        let category: String
        let createdDate: Date
        let color: String
        let isFavorite: Bool
    }
    
    struct TripData: Codable {
        let id: UUID
        let fromEventID: String  // Event IDs are Strings
        let toEventID: String    // Event IDs are Strings
        let departureDate: Date
        let arrivalDate: Date
        let distance: Double
        let transportMode: String
        let co2Emissions: Double
        let notes: String
        let isAutoGenerated: Bool
    }
}
