//
//  TestDataFactory.swift
//  LocTracTests
//
//  Shared test data helpers for all unit tests.
//  Provides factory methods for creating test models with sensible defaults.
//

import Foundation
@testable import LocTrac

enum TestDataFactory {

    // MARK: - Locations

    static func makeLocation(
        id: String = UUID().uuidString,
        name: String = "Test Location",
        city: String? = "Denver",
        state: String? = "Colorado",
        latitude: Double = 39.7392,
        longitude: Double = -104.9903,
        country: String? = "United States",
        countryCode: String? = "US",
        theme: Theme = .blue,
        imageIDs: [String]? = nil
    ) -> Location {
        Location(
            id: id,
            name: name,
            city: city,
            state: state,
            latitude: latitude,
            longitude: longitude,
            country: country,
            countryCode: countryCode,
            theme: theme,
            imageIDs: imageIDs
        )
    }

    static func makeOtherLocation() -> Location {
        Location(
            id: "other",
            name: "Other",
            city: nil,
            latitude: 0,
            longitude: 0,
            theme: .gray
        )
    }

    // MARK: - Events

    static func makeEvent(
        id: String = UUID().uuidString,
        eventType: Event.EventType = .stay,
        date: Date = Date().startOfDay,
        location: Location? = nil,
        city: String? = nil,
        latitude: Double = 39.7392,
        longitude: Double = -104.9903,
        country: String? = "United States",
        state: String? = "Colorado",
        note: String = "Test event",
        people: [Person] = [],
        activityIDs: [String] = [],
        isGeocoded: Bool = true,
        imageIDs: [String] = []
    ) -> Event {
        let loc = location ?? makeLocation()
        return Event(
            id: id,
            eventType: eventType,
            date: date,
            location: loc,
            city: city,
            latitude: latitude,
            longitude: longitude,
            country: country,
            state: state,
            note: note,
            people: people,
            activityIDs: activityIDs,
            affirmationIDs: [],
            isGeocoded: isGeocoded,
            imageIDs: imageIDs
        )
    }

    /// Creates an event at the "Other" location with custom city/country
    static func makeOtherEvent(
        date: Date = Date().startOfDay,
        city: String = "Paris",
        state: String? = nil,
        country: String = "France",
        latitude: Double = 48.8566,
        longitude: Double = 2.3522,
        note: String = "Other city event"
    ) -> Event {
        makeEvent(
            location: makeOtherLocation(),
            city: city,
            latitude: latitude,
            longitude: longitude,
            country: country,
            state: state,
            note: note
        )
    }

    // MARK: - Trips

    static func makeTrip(
        fromEventID: String = UUID().uuidString,
        toEventID: String = UUID().uuidString,
        departureDate: Date = Date().startOfDay,
        arrivalDate: Date = Date().startOfDay,
        distance: Double = 500,
        transportMode: TransportMode = .car,
        notes: String = "Test trip",
        isAutoGenerated: Bool = false
    ) -> Trip {
        Trip(
            fromEventID: fromEventID,
            toEventID: toEventID,
            departureDate: departureDate,
            arrivalDate: arrivalDate,
            distance: distance,
            transportMode: transportMode,
            notes: notes,
            isAutoGenerated: isAutoGenerated
        )
    }

    // MARK: - Activities

    static func makeActivity(
        name: String = "Test Activity"
    ) -> Activity {
        Activity(name: name)
    }

    // MARK: - People

    static func makePerson(
        displayName: String = "John Doe"
    ) -> Person {
        Person(displayName: displayName)
    }

    // MARK: - Event Types

    static func makeEventType(
        name: String = "camping",
        displayName: String = "Camping",
        sfSymbol: String = "tent.fill",
        colorName: String = "green"
    ) -> EventTypeItem {
        EventTypeItem(
            name: name,
            displayName: displayName,
            sfSymbol: sfSymbol,
            colorName: colorName
        )
    }

    // MARK: - Sample Backup File

    /// Loads the real sample_backup.json from the Fixtures directory.
    /// Contains 1590 events, 7 locations, 384 trips, 13 activities, 25 affirmations, 6 eventTypes.
    /// Returns nil if the file is not found in the test bundle.
    static var sampleBackupData: Data? {
        // Try loading from the test bundle (File System Synchronized Group)
        let testDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        let fixtureURL = testDir.appendingPathComponent("Fixtures/sample_backup.json")
        return try? Data(contentsOf: fixtureURL)
    }

    // MARK: - Fixture JSON

    /// Minimal valid backup JSON for import testing
    static var minimalBackupJSON: Data {
        Data("""
        {
            "locations": [],
            "events": []
        }
        """.utf8)
    }

    /// Backup JSON with known test data for deterministic testing
    static var fixtureBackupJSON: Data {
        Data("""
        {
            "locations": [
                {
                    "id": "loc-home",
                    "name": "Home",
                    "city": "Denver",
                    "state": "Colorado",
                    "latitude": 39.7392,
                    "longitude": -104.9903,
                    "country": "United States",
                    "countryCode": "US",
                    "theme": "blue"
                },
                {
                    "id": "loc-other",
                    "name": "Other",
                    "city": null,
                    "latitude": 0,
                    "longitude": 0,
                    "theme": "gray"
                }
            ],
            "events": [
                {
                    "locationID": "loc-home",
                    "id": "evt-001",
                    "eventType": "stay",
                    "date": "2026-01-15T00:00:00Z",
                    "latitude": 39.7392,
                    "longitude": -104.9903,
                    "country": "United States",
                    "state": "Colorado",
                    "note": "Fixture event 1",
                    "activityIDs": [],
                    "affirmationIDs": [],
                    "imageIDs": []
                },
                {
                    "locationID": "loc-home",
                    "id": "evt-002",
                    "eventType": "stay",
                    "date": "2026-01-16T00:00:00Z",
                    "latitude": 39.7392,
                    "longitude": -104.9903,
                    "country": "United States",
                    "state": "Colorado",
                    "note": "Fixture event 2",
                    "activityIDs": [],
                    "affirmationIDs": [],
                    "imageIDs": []
                },
                {
                    "locationID": "loc-other",
                    "id": "evt-003",
                    "eventType": "vacation",
                    "date": "2026-02-10T00:00:00Z",
                    "city": "Cabo San Lucas",
                    "latitude": 22.8905,
                    "longitude": -109.9167,
                    "country": "Mexico",
                    "note": "Fixture vacation",
                    "activityIDs": [],
                    "affirmationIDs": [],
                    "imageIDs": []
                }
            ],
            "activities": [
                {"id": "act-001", "name": "Golf"},
                {"id": "act-002", "name": "Hiking"}
            ],
            "affirmations": [
                {
                    "id": "aff-001",
                    "text": "Test affirmation",
                    "category": "gratitude",
                    "createdDate": "2026-01-01T00:00:00Z",
                    "color": "blue",
                    "isFavorite": false
                }
            ],
            "trips": [
                {
                    "id": "E7B3A1D2-4F56-4C8E-9A2B-1D3E5F7A9B0C",
                    "fromEventID": "evt-002",
                    "toEventID": "evt-003",
                    "departureDate": "2026-01-16T00:00:00Z",
                    "arrivalDate": "2026-02-10T00:00:00Z",
                    "distance": 1200,
                    "transportMode": "plane",
                    "co2Emissions": 540.0,
                    "notes": "Denver to Cabo",
                    "isAutoGenerated": true
                }
            ],
            "eventTypes": [
                {"id": "et-001", "name": "stay", "displayName": "Stay", "sfSymbol": "bed.double.fill", "colorName": "red", "isBuiltIn": true},
                {"id": "et-002", "name": "vacation", "displayName": "Vacation", "sfSymbol": "airplane", "colorName": "green", "isBuiltIn": true}
            ]
        }
        """.utf8)
    }

    /// Simulates a v1.3 backup (no activities, affirmations, trips, eventTypes)
    static var legacyV13BackupJSON: Data {
        Data("""
        {
            "locations": [
                {
                    "id": "loc-legacy",
                    "name": "Legacy Place",
                    "city": "Boulder",
                    "latitude": 40.0150,
                    "longitude": -105.2705,
                    "theme": "green"
                }
            ],
            "events": [
                {
                    "locationID": "loc-legacy",
                    "id": "evt-legacy",
                    "eventType": "stay",
                    "date": "2025-06-15T00:00:00Z",
                    "latitude": 40.0150,
                    "longitude": -105.2705,
                    "note": "Legacy event",
                    "activityIDs": [],
                    "affirmationIDs": []
                }
            ]
        }
        """.utf8)
    }
}
