import Foundation

struct Import: Codable {
    struct Event: Codable {
        var locationID: String
        let id: String
        var eventType: String
        let date: Date
        var city: String
        var latitude: Double
        var longitude: Double
        var country: String? // NEW: Country field for events
        var note: String
        var people: [Person]? // optional for backward compatibility
        var activityIDs: [String]? // NEW: optional for backward compatibility
    }
    
    struct Location: Codable {
        let id: String
        var name: String
        var city: String?
        var latitude: Double
        var longitude: Double
        var country: String?  // <-- Country support
        var theme: String
        var imageIDs: [String]? // existing
    }
    
    struct ActivityData: Codable {
        let id: String
        let name: String
    }
    
    struct TripData: Codable {
        let id: UUID
        let fromEventID: String  // Event IDs are Strings
        let toEventID: String    // Event IDs are Strings
        let departureDate: Date
        let arrivalDate: Date
        let distance: Double
        let transportMode: String
        let co2Emissions: Double
        let notes: String
        let isAutoGenerated: Bool
    }
    
    let events: [Event]
    let locations: [Location]
    let activities: [ActivityData]? // NEW (optional for old seed files)
    let trips: [TripData]? // NEW (optional for old seed files)
}

struct Export: Codable {
    let locations: [LocationData]
    let events: [EventData]
    let activities: [ActivityData] // NEW
    let trips: [TripData] // NEW
    
    init(locations: [Location], events: [Event], activities: [Activity], trips: [Trip]) {
        self.locations = locations.map {
            LocationData(id: $0.id,
                         name: $0.name,
                         city: $0.city,
                         latitude: $0.latitude,
                         longitude: $0.longitude,
                         country: $0.country,
                         theme: $0.theme.rawValue,
                         imageIDs: $0.imageIDs)
        }
        self.events = events.map {
            EventData(locationID: $0.location.id,
                      id: $0.id,
                      eventType: $0.eventType,
                      date: $0.date,
                      city: $0.city ?? "",
                      latitude: $0.latitude,
                      longitude: $0.longitude,
                      country: $0.country, // NEW: Export event's country
                      note: $0.note,
                      people: $0.people,
                      activityIDs: $0.activityIDs)
        }
        self.activities = activities.map { ActivityData(id: $0.id, name: $0.name) }
        self.trips = trips.map {
            TripData(
                id: $0.id,
                fromEventID: $0.fromEventID,
                toEventID: $0.toEventID,
                departureDate: $0.departureDate,
                arrivalDate: $0.arrivalDate,
                distance: $0.distance,
                transportMode: $0.transportMode,
                co2Emissions: $0.co2Emissions,
                notes: $0.notes,
                isAutoGenerated: $0.isAutoGenerated
            )
        }
    }
    
    struct LocationData: Codable {
        let id: String
        let name: String
        let city: String?
        let latitude: Double
        let longitude: Double
        let country: String?  // <-- Country support
        let theme: String
        let imageIDs: [String]?
    }
    
    struct EventData: Codable {
        let locationID: String
        let id: String
        var eventType: String
        let date: Date
        let city: String
        let latitude: Double
        let longitude: Double
        let country: String? // NEW: Country field
        let note: String
        let people: [Person]? // existing
        let activityIDs: [String] // NEW
    }
    
    struct ActivityData: Codable {
        let id: String
        let name: String
    }
    
    struct TripData: Codable {
        let id: UUID
        let fromEventID: String  // Event IDs are Strings
        let toEventID: String    // Event IDs are Strings
        let departureDate: Date
        let arrivalDate: Date
        let distance: Double
        let transportMode: String
        let co2Emissions: Double
        let notes: String
        let isAutoGenerated: Bool
    }
}
